name: Build and test

on:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: leanprover/lean-action@v1
        with:
          build: true
          test: true
