name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: leanprover/lean-action@c544e89643240c6b398f14a431bcdc6309e36b3e # v1.4.0
        with:
          build: true
          test: true

  build:
    needs: test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: hopscotch-linux-x86_64
            binary: hopscotch
          - os: macos-15-intel
            artifact: hopscotch-macos-x86_64
            binary: hopscotch
          - os: macos-latest
            artifact: hopscotch-macos-arm64
            binary: hopscotch
          - os: windows-latest
            artifact: hopscotch-windows-x86_64
            binary: hopscotch.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: leanprover/lean-action@c544e89643240c6b398f14a431bcdc6309e36b3e # v1.4.0
        with:
          build-args: hopscotch
          test: false
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ matrix.artifact }}
          path: .lake/build/bin/${{ matrix.binary }}
          if-no-files-found: error

  release:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      - name: Rename binaries
        run: |
          mv hopscotch-linux-x86_64/hopscotch hopscotch-linux-x86_64/hopscotch-linux-x86_64
          mv hopscotch-macos-x86_64/hopscotch hopscotch-macos-x86_64/hopscotch-macos-x86_64
          mv hopscotch-macos-arm64/hopscotch hopscotch-macos-arm64/hopscotch-macos-arm64
          mv hopscotch-windows-x86_64/hopscotch.exe hopscotch-windows-x86_64/hopscotch-windows-x86_64.exe
      - uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
        with:
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: |
            hopscotch-linux-x86_64/hopscotch-linux-x86_64
            hopscotch-macos-x86_64/hopscotch-macos-x86_64
            hopscotch-macos-arm64/hopscotch-macos-arm64
            hopscotch-windows-x86_64/hopscotch-windows-x86_64.exe
